-- Alinea Rol con prisma/schema.prisma sin reemplazar el enum ni modificar usuarios.
-- Los valores nuevos se pueden usar después del COMMIT de esta migración.
ALTER TYPE "Rol" ADD VALUE IF NOT EXISTS 'CLIENTE_ADMIN' AFTER 'CLIENTE';
ALTER TYPE "Rol" ADD VALUE IF NOT EXISTS 'CLIENTE_COOR' AFTER 'CLIENTE_ADMIN';
ALTER TYPE "Rol" ADD VALUE IF NOT EXISTS 'ARRASTRE_TORREON' AFTER 'CLIENTE_COOR';
ALTER TYPE "Rol" ADD VALUE IF NOT EXISTS 'MAQUINISTA_ARRASTRE' AFTER 'MAQUINISTA';
ALTER TYPE "Rol" ADD VALUE IF NOT EXISTS 'COMERCIAL' AFTER 'MAQUINISTA_ARRASTRE';
